[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
                to = "websecure"
                scheme = "https"
                permanent = true
    [entryPoints.websecure]
        address = ":443"
        [entryPoints.websecure.http.tls]
        

[providers]
    [providers.file]
        directory = "/etc/traefik/conf.d"
        watch = true
    [providers.docker]


[api]
    dashboard = true
    debug = false

[accessLog]
    filePath = "/etc/traefik/logs/access.log"
    bufferingSize = 100

[global]
    checkNewVersion = false
    sendAnonymousUsage = false

[serversTransport]
    insecureSkipVerify = true
    rootCAs = ["/etc/traefik/certs/ca.pem"]

[experimental]
    http3 = true


